refactor

diff --git a/gen-sailfish-patch b/gen-sailfish-patch
--- a/gen-sailfish-patch
+++ b/gen-sailfish-patch
@@ -89,38 +89,62 @@ while [[ $# > 0 ]]; do
     shift
 done
 
-script_dir=$(dirname "$(readlink -f "$0")")
-json_file="$script_dir/patch.json"
-gitignore_file="$script_dir/gitignore"
-spec_file="$script_dir/patch.spec"
+template_dir="$(dirname "$(readlink -f "$0")")/templates"
+
+if [[ ! -d "$template_dir" ]]; then
+    echo "error: template directory not found!"
+    exit 1
+fi
+
+json_file="$template_dir/patch.json"
+gitignore_file="$template_dir/gitignore"
+spec_file="$template_dir/patch.spec"
 
 out_dir="build"
 patch_dir="$out_dir/patch"
 rpm_dir="$out_dir/rpm"
+prefix_file="$out_dir/dir"
+
+
+if [[ ! -d .git ]]; then
+    echo "error: not in the root directory of a Git repository!"
+    exit 2
+fi
+
+project="$(basename "$(pwd)")"
 
 orig_branch="$(git branch --list | grep -E '^\s*original$')"
-if [ -z "$orig_branch" ]; then
-    echo "Missing 'original' branch."
-    echo "Create this branch and commit the original qml files without changes."
-    echo "From there, the diff is created"
+
+if [[ -z "$orig_branch" ]]; then
+    echo "error: missing 'original' branch!"
+    echo "Create this branch and commit the original QML files without changes."
+    echo "The diff is created based on this branch."
     exit 1
 fi
 
-[ -f dir ] && prefix_dir="$(cat dir | head -n 1)" || prefix_dir="/"
+if [[ -f "$prefix_file" ]]; then
+    prefix_dir="$(cat "$prefix_file" | head -n 1)"
+else
+    prefix_dir="/"
+    echo "$prefix_dir" > "$prefix_file"
+fi
 
-if [ ! -d "$out_dir" ]; then
+if [[ ! -d "$out_dir" ]]; then
     mkdir -p "$out_dir"
+fi
+
+if [[ ! -f "$out_dir/.gitignore" ]]; then
     cp "$gitignore_file" "$out_dir/.gitignore"
 fi
 
-if [ ! -d "$rpm_dir" ]; then
+if [[ ! -d "$rpm_dir" ]]; then
     mkdir -p "$rpm_dir"
-    cp "$spec_file" "$rpm_dir/TODO.spec"
+    sed "s/Name: NAME/Name: $project/g;" "$spec_file" > "$rpm_dir/$project.spec"
 fi
 
-if [ ! -d "$patch_dir" ]; then
+if [[ ! -d "$patch_dir" ]]; then
     mkdir -p "$patch_dir"
     cp "$json_file" "$patch_dir/patch.json"
 fi
 
-git diff original --src-prefix="a$prefix_dir" --dst-prefix="b$prefix_dir" **/*.qml > $patch_dir/unified_diff.patch
+git diff original --src-prefix="a$prefix_dir" --dst-prefix="b$prefix_dir" -- . ':(exclude)build/*' > "$patch_dir/unified_diff.patch"
