Show default config value for missing required fields

diff --git a/sailfish-patch b/sailfish-patch
--- a/sailfish-patch
+++ b/sailfish-patch
@@ -490,6 +490,75 @@ select_range() { # 1: from pattern, 2: to pattern
     awk "/$from_pattern/{flag=1;next}/$to_pattern/{flag=0}flag"
 }
 
+require_global_config() {
+    if [[ -z "$SF_PATCH_GLOBAL_DEFAULTS" ]]; then
+        echo "internal error: \$SF_PATCH_GLOBAL_DEFAULTS is empty" >&2
+        return 1
+    fi
+
+    mkdir -p "$(dirname "$SF_PATCH_GLOBAL_DEFAULTS")"
+
+    if [[ ! -f "$SF_PATCH_GLOBAL_DEFAULTS" ]]; then
+        cat <<EOF > "$SF_PATCH_GLOBAL_DEFAULTS"
+# Default configuration values for sailfish-patch
+#
+# The values configured here will be used as default values in new
+# configuration files generated by sailfish-patch. They have no effect for already
+# existing files.
+#
+# Only the following (single-line) fields can be configured here:
+$(echo -n "$check_allowed_in_global_config" | tr '\n' ' ' | sed 's/^/# /g;s/ $//;')
+#
+# Lines starting with '#' will be ignored.
+# Entry lines are key-value pairs joined by ':' (one entry per line).
+
+# Version: 1.0.0
+# Release: 1
+# License: GPL-3.0-or-later
+
+# Prefix: /usr/share
+# Maintainer: Foo Bar
+# DiscussionLink: https://discuss.example.org/foobar
+# DonationsLink: https://donate.example.org/foobar
+# SourcesLink: https://sources.example.org/foobar
+
+# [keep this line: sailfish-patch 2.5.0 (2021-11-28)]
+# kate: syntax SailfishOS Patch
+EOF
+    fi
+}
+
+# return the default configuration value for field $1
+# The function takes globally configured defaults into account and returns,
+# if available, the global value or else the dummy value.
+__get_default_config() { # 1: field/key
+    require_global_config || exit 1
+    [[ -z "$1" ]] && return 1
+
+    if echo -n "$check_allowed_in_global_config" | grep -Pqoe "^$1$" && grep -Pqoe "^$1:" "$SF_PATCH_GLOBAL_DEFAULTS"; then
+        value="$(grep -Pe "^$1:" "$SF_PATCH_GLOBAL_DEFAULTS" | cut -d\: -f2-)"
+        value="$(trim "$value")"
+        echo "$value"
+    elif [[ -n "${default_config_values[$1]}" ]]; then
+        value="${default_config_values[$1]}"
+        type="${value%%@*}"
+
+        if [[ "$value" == [ms]"@dummy" ]]; then
+            value="${check_default_dummies[$1]}"
+        else
+            value="${value#*@}"
+        fi
+
+        if [[ "$type" == m ]]; then
+            echo "$value" | sed 's/^/- /;s/|/\n- /g'
+        else
+            echo "$value"
+        fi
+    else
+        echo "error: default value for invalid key requested ($1)" >&2
+        return 1
+    fi
+}
 
 if [[ "$list_releases" == true ]]; then
     # a list of all Sailfish versions supported by patchmanager
@@ -805,6 +874,11 @@ if [[ "$check_config" == true ]]; then
         [[ -z "$r" ]] && continue
         if ! printf "%s\n" "${keys_found[@]}"  | grep -Pqoe "^$r"; then
             echo "error: required field '$r' is missing" >&2
+
+            if default="$(__get_default_config "License")"; then
+                printf -- "%s\n" "       the default value for new config files is: $default" >&2
+            fi
+
             error=true
         fi
     done
@@ -1440,78 +1514,6 @@ require_config() { # 1: expected config file location
     fi
 
     return 0
-}
-
-# NOTE place above __save_template_config?
-require_global_config() {
-    if [[ -z "$SF_PATCH_GLOBAL_DEFAULTS" ]]; then
-        echo "internal error: \$SF_PATCH_GLOBAL_DEFAULTS is empty" >&2
-        return 1
-    fi
-
-    mkdir -p "$(dirname "$SF_PATCH_GLOBAL_DEFAULTS")"
-
-    if [[ ! -f "$SF_PATCH_GLOBAL_DEFAULTS" ]]; then
-        cat <<EOF > "$SF_PATCH_GLOBAL_DEFAULTS"
-# Default configuration values for sailfish-patch
-#
-# The values configured here will be used as default values in new
-# configuration files generated by sailfish-patch. They have no effect for already
-# existing files.
-#
-# Only the following (single-line) fields can be configured here:
-$(echo -n "$check_allowed_in_global_config" | tr '\n' ' ' | sed 's/^/# /g;s/ $//;')
-#
-# Lines starting with '#' will be ignored.
-# Entry lines are key-value pairs joined by ':' (one entry per line).
-
-# Version: 1.0.0
-# Release: 1
-# License: GPL-3.0-or-later
-
-# Prefix: /usr/share
-# Maintainer: Foo Bar
-# DiscussionLink: https://discuss.example.org/foobar
-# DonationsLink: https://donate.example.org/foobar
-# SourcesLink: https://sources.example.org/foobar
-
-# [keep this line: sailfish-patch 2.5.0 (2021-11-28)]
-# kate: syntax SailfishOS Patch
-EOF
-    fi
-}
-
-# return the default configuration value for field $1
-# The function takes globally configured defaults into account and returns,
-# if available, the global value or else the dummy value.
-# NOTE place above __save_template_config?
-__get_default_config() { # 1: field/key
-    require_global_config || exit 1
-    [[ -z "$1" ]] && return 1
-
-    if echo -n "$check_allowed_in_global_config" | grep -Pqoe "^$1$" && grep -Pqoe "^$1:" "$SF_PATCH_GLOBAL_DEFAULTS"; then
-        value="$(grep -Pe "^$1:" "$SF_PATCH_GLOBAL_DEFAULTS" | cut -d\: -f2-)"
-        value="$(trim "$value")"
-        echo "$value"
-    elif [[ -n "${default_config_values[$1]}" ]]; then
-        value="${default_config_values[$1]}"
-        type="${value%%@*}"
-
-        if [[ "$value" == [ms]"@dummy" ]]; then
-            value="${check_default_dummies[$1]}"
-        else
-            value="${value#*@}"
-        fi
-
-        if [[ "$type" == m ]]; then
-            echo "$value" | sed 's/^/- /;s/|/\n- /g'
-        else
-            echo "$value"
-        fi
-    else
-        echo "error: default value for invalid key requested ($1)" >&2
-        return 1
-    fi
 }
 
 # return unchecked base config path to be used
