enforce rules for Release field

diff --git a/sailfish-patch b/sailfish-patch
--- a/sailfish-patch
+++ b/sailfish-patch
@@ -287,7 +287,7 @@ if [[ "$check_config" == true ]]; then
                     echo "note: no value given for '$key'"
                 fi
             ;;
-            DisplayName|Maintainer|Summary|Release)
+            DisplayName|Maintainer|Summary)
                 # must not be empty
                 if [[ -z "$value" ]]; then
                     echo "error: required field '$key' is empty" >/dev/stderr
@@ -330,6 +330,18 @@ if [[ "$check_config" == true ]]; then
                 # needs special rules
                 if ! echo "$value" | grep -Pqoe '^[0-9]+\.[0-9]+\.[0-9]+'; then
                     echo "error: version number must consist of three numbers separated by dots (X.Y.Z; line $count)" >/dev/stderr
+                    error=true
+                fi
+            ;;
+            Release)
+                # must not be empty
+                if [[ -z "$value" ]]; then
+                    echo "error: required field '$key' is empty" >/dev/stderr
+                    error=true
+                fi
+                # needs special rules
+                if ! echo "$value" | grep -Pqoe '^[1-9][0-9]*'; then
+                    echo "error: release number must be exactly one number without leading zeros (XYZ; line $count)" >/dev/stderr
                     error=true
                 fi
             ;;
