Show detailed error messages if deployment fails

diff --git a/sailfish-patch b/sailfish-patch
--- a/sailfish-patch
+++ b/sailfish-patch
@@ -2417,17 +2417,34 @@ else
         package_name="$(get_single_config "$config" "PackageName")"
 
         scp "$rpm" "$SF_PATCH_REMOTE_USERNAME@$SF_PATCH_SSH_TARGET:$SF_PATCH_REMOTE_PATH"
-        head -1 "$SF_PATCH_PASSFILE" | ssh -o ConnectTimeout=3 "$SF_PATCH_SSH_TARGET" "devel-su /usr/sbin/patchmanager -u '$package_name'"
-        head -1 "$SF_PATCH_PASSFILE" | ssh -o ConnectTimeout=3 "$SF_PATCH_SSH_TARGET" "devel-su rpm --reinstall -vh '$SF_PATCH_REMOTE_PATH/$(basename "$rpm")'"
-        head -1 "$SF_PATCH_PASSFILE" | ssh -o ConnectTimeout=3 "$SF_PATCH_SSH_TARGET" "devel-su /usr/sbin/patchmanager -a '$package_name'"
+        { { head -1 "$SF_PATCH_PASSFILE" | ssh -o ConnectTimeout=3 "$SF_PATCH_SSH_TARGET" "devel-su /usr/sbin/patchmanager -u '$package_name'"; } || {
+            echo "error: failed to ensure patch is unapplied" >/dev/stderr && false
+        }; } &&\
+        { { head -1 "$SF_PATCH_PASSFILE" | ssh -o ConnectTimeout=3 "$SF_PATCH_SSH_TARGET" "devel-su rpm --erase '$package_name'"; } || {
+            echo "error: failed to ensure patch package is not installed" >/dev/stderr && false
+        }; } &&\
+        { { head -1 "$SF_PATCH_PASSFILE" | ssh -o ConnectTimeout=3 "$SF_PATCH_SSH_TARGET" "devel-su rpm -ivh '$SF_PATCH_REMOTE_PATH/$(basename "$rpm")'"; } || {
+            echo "error: failed to install patch package" >/dev/stderr && false
+        }; } &&\
+        { { head -1 "$SF_PATCH_PASSFILE" | ssh -o ConnectTimeout=3 "$SF_PATCH_SSH_TARGET" "devel-su /usr/sbin/patchmanager -a '$package_name'"; } || {
+            echo "error: failed to apply patch" >/dev/stderr && false
+        }; }
+
+        install_success=$?
 
         needs_keyboard="$(get_multi_config "$config" "Requires" | paste -s -d'\n' - <(get_multi_config "$config" "SourcePackages") | grep -oe '^jolla-keyboard')"
         if [[ -n "$needs_keyboard" ]]; then
             echo "restarting keyboard service..."
-            head -1 "$SF_PATCH_PASSFILE" | ssh -o ConnectTimeout=3 "$SF_PATCH_SSH_TARGET" "devel-su systemctl --user restart maliit-server"
+            head -1 "$SF_PATCH_PASSFILE" | ssh -o ConnectTimeout=3 "$SF_PATCH_SSH_TARGET" "devel-su systemctl --user restart maliit-server" || {
+                echo "warning: failed to restart keyboard service (maliit-server)" >/dev/stderr && false
+            }
         fi
 
-        echo "patch deployed"
+        if (( $install_success > 0 )); then
+            echo "failed to deploy patch" >/dev/stderr
+        else
+            echo "patch deployed"
+        fi
     fi
 
     __wizard_load() { # 1: type, 2: title, 3: key
